In [11]:
import numpy as np
from time import time

In [12]:
print("Enter dimensions")
print("Enter m1 : ",end=" ")
m1=int(input())
print("Enter n1 : ",end=" ")
n1=int(input())
print("Enter r1 : ",end=" ")
r1=int(input())
print("Enter m2 : ",end=" ")
m2=int(input())
print("Enter n2 : ",end=" ")
n2=int(input())
print("Enter r2 : ",end=" ")

r2=int(input())

Enter dimensions
Enter m1 :  Enter n1 :  Enter r1 :  Enter m2 :  Enter n2 :  Enter r2 :  

In [13]:
tensor1=np.random.normal(0,1,(m1,n1,r1))
tensor2=np.random.rand(m2,n2,r2)
print(tensor1)
print()
print(tensor2)

[[[ 0.76368489 -0.93027596 -0.21136636]
  [-0.53988927  0.02926394  0.45123863]
  [-0.20409001  0.15683354  0.89284336]]

 [[ 0.74028131  1.26671515 -0.7821946 ]
  [ 0.25617697  2.6895436   0.14448085]
  [-2.29289401 -0.76962538 -0.24882023]]

 [[ 0.0076769  -1.89655659 -1.71582864]
  [ 0.66048275 -1.06397483  0.07416108]
  [-2.03999954  0.35833237  0.20780525]]]

[[[9.87683664e-01 7.39289551e-01 8.18002189e-01]
  [1.83360817e-04 9.67341546e-01 9.78568814e-01]
  [4.15887321e-01 9.53992201e-01 9.38298547e-01]]

 [[2.53612723e-03 7.38550481e-01 4.99203686e-01]
  [4.99928700e-01 1.33030902e-01 6.73648297e-01]
  [9.57387817e-01 5.91593768e-02 1.16480182e-01]]

 [[4.56449782e-01 5.76172637e-01 5.79663584e-01]
  [1.14934302e-01 8.14312238e-01 3.02533999e-01]
  [9.67388002e-01 8.57571601e-01 8.63436498e-01]]]


In [14]:
c1=np.random.randint(1,11)
c2=np.random.randint(1,11)
c3=np.random.randint(1,11)
print("c1 : "+str(c1)+" c2 : "+str(c2)+" c3 : "+str(c3))
currentTime=time()
print(np.dot(c1,tensor1)+np.dot(c2,tensor2)+c3)
print("Time for Linear Combination : ",end=" ")
print(time()-currentTime)

c1 : 6 c2 : 10 c3 : 1
[[[15.45894599  2.81123975  7.9118237 ]
  [-2.23750204 10.84899907 13.49311992]
  [ 3.93433314 11.48092327 15.74004564]]

 [[ 5.46704912 15.98579574  1.29886927]
  [ 7.53634885 18.46757061  8.60336809]
  [-3.18348587 -3.02615851  0.67188042]]

 [[ 5.61055923 -4.61761318 -3.49833601]
  [ 6.11223955  2.75927342  4.47030648]
  [-1.56611721 11.72571024 10.88119646]]]
Time for Linear Combination :  0.0006628036499023438
