In [116]:
import math
import copy
import numpy as np
import matplotlib.pyplot as plt


In [117]:
# load our dataset
x = np.array([0,1,2,3,1,1.5])             # features
y = np.array([1,2,1.5,2,1,2])             # target value


In [118]:
def xi_sum(x,d):
    sum_arr = 0
    for i in range(0,len(x)):
        sum_arr = sum_arr +  x[i]**d
    return sum_arr
    

In [119]:
coeff_matrix = np.array([[xi_sum(x,4) , xi_sum(x,3),xi_sum(x,2)],
                         [xi_sum(x,3) , xi_sum(x,2),xi_sum(x,1)],
                         [xi_sum(x,2) , xi_sum(x,1),len(x)]])

In [120]:
coeff_matrix

array([[104.0625,  40.375 ,  17.25  ],
       [ 40.375 ,  17.25  ,   8.5   ],
       [ 17.25  ,   8.5   ,   6.    ]])

In [121]:
def xi_yi_sum(x,y,d1,d2):
    sum_arr = 0
    for i in range(0, len(x)):
        sum_arr = sum_arr + (x[i]**d1)*(y[i]**d2)
    return sum_arr


In [122]:
y_mat =  np.array([[xi_yi_sum(x,y,2,1)],
                    [xi_yi_sum(x,y,1,1)],
                    [xi_yi_sum(x,y,0,1)]])

In [123]:
y_mat

array([[31.5],
       [15. ],
       [ 9.5]])

In [124]:
inv_coeff_matrix = np.linalg.inv(coeff_matrix)
a_b_c = np.dot(inv_coeff_matrix,y_mat)

In [125]:
a_b_c


array([[-0.09298246],
       [ 0.58052632],
       [ 1.02824561]])

In [126]:
a = a_b_c[0][0]
b = a_b_c[1][0]
c = a_b_c[2][0]

In [127]:
def y_pred_i(x,y,a,b,c):
    y_i = []
    for i in range(0,len(y)):
        y_i.append((a*(x[i]**2)) + b*x[i] + c)
    return y_i  

In [128]:
y_i = y_pred_i(x, y, a, b, c)

In [129]:
y_i

[1.0282456140350864,
 1.5157894736842106,
 1.8173684210526317,
 1.9329824561403497,
 1.5157894736842106,
 1.689824561403509]

In [130]:
error = 0
error = np.sum((y_i - y)**2)

In [131]:
error

0.7027192982456141